version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
